Config file changes This file can now be pushed to the main branch. The following changes have taken place: 1) Removed my personal data. 2) Made it compliant with pydantic 2. This involved:     a) Changing the way of noting optional strings (now 'none' strings). This is as elegant as is possible.     b) Updating the imports. Origin code results in "pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.7/migration/#basesettings-has-moved-to-pydantic-settings for more details.     c) converting urls using the str() method. Origin code results in AttributeError: 'pydantic_core._pydantic_core.Url' object has no attribute 'decode' For further information visit https://errors.pydantic.dev/2.7/u/import-error"
New developers will still need to fill out the mail_address, mail_password, mail_username, mail_port and secret_key before they can run the code. This is by design, though.

Hope this saves time, Mawoka!